### ISSUE TITLE
Composer was not installed on ubuntu 20.04

### ISSUE THREAD

**Issue by T100D** [BookStackApp/devops#28]
Hi all,

I recently installed BookStack 0.30.0 on a fresh ubuntu 20.04 desktop environment with the script
mentioned on the site and present here in this branch.

When updating to 0.30.02 with command:
    `sudo git pull origin release && composer install --no-dev && php artisan migrate` 
composer did not appeared to be installed, while installation is present in the installation script.

It could be installed directly with `sudo apt install composer` (Version 1.10.1 shall be installed)

This looks like the installation script could be changed.

Second on updating, it might be okay to mention sudo in front of the updating commands to overcome possible faults in updating BookStack.

**Comment by ssddanbrown** [comment]
Thanks for reporting @T100D.

I've now updated the Ubuntu20.04 install script to install composer globally.
Composer was installed before bust just local as `composer.phar` within the bookstack install folder.
I'd recommend not using the `apt install` version of composer since it quickly gets out of date.

I'll think about how to mention the update commands, The `sudo` element won't be applicable nor recommended for all set-ups so will think about how to display that.
