### ISSUE TITLE
uninstall BookStackApp

### ISSUE THREAD

**Issue by jiespring** [BookStackApp/devops#31]
After the installation of the program, I lost my existing website database. May I ask how to uninstall your program?

**Comment by ssddanbrown** [comment]
Hi @jiespring,
It really depends on how you installed BookStack, what operating system you're running, and what you had installing/running beforehand. If you can confirm those points I may be able to provide some guidance.

**Comment by ssddanbrown** [comment]
This is why our installation instruction page states:

> This script is ONLY FOR A FRESH OS, it will install Apache, MySQL 5.7 & PHP-7.4 and could OVERWRITE any existing web setup on the machine

Since you've installed on existing system I don't know the previous state enough to provide instructions to get to the exact previous state. Nor do I know what may have conflicted upon install. I can only offer the below guidance. Of course backup your system first.

- BookStack files are installed to `/var/www/bookstack`. Therefore they can be removed via `sudo rm -rf /var/www/bookstack`.
- An apache virtualhost config is setup at `/etc/apache2/sites-available/bookstack.conf`. This can be removed via `sudo a2ensite bookstack.conf` and `sudo rm /etc/apache2/sites-available/bookstack.conf` and then `sudo systemctl restart apache2`.
- Within MySQL, a user and database of the name `bookstack` is created. You might want to delete these.
- The packages installed in the script can be seen on [these lines](https://github.com/BookStackApp/devops/blob/4ffe766ec0deb9c9625a12e068bbb011f58db37d/scripts/installation-ubuntu-20.04.sh#L30-L31). You may want to uninstall these but you may have been relying on some of these packages before running the script.

I'm not really sure how the install script would have damaged the database or lost the existing website's database. The script does install `mysql-server-8.0`. If you had an alternative database running then it may be that `mysql-server-8.0` is now taking precedence. You could attempt uninstalling `mysql-server-8.0` then restarting the machine to see if your other database comes back up. Of course I'm writing this without any context of what would have been installed there so just guessing.
